<a href="https://colab.research.google.com/github/Joshi-Atharva/Sentiment-analysis/blob/main/Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
# Mounting the drive to use the files and images
import os
import csv
os.chdir('/content/drive/MyDrive/Sentiment analysis/')
print(os.listdir())
# rom extract_csv import extract_csv, split
from extract_bin import extract_bin, split
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
['train_set.txt', 'train_set_sentiment.txt', '__pycache__', 'trainDataSet.txt', 'extract.py', 'imdb_labelled.txt', 'amazon_cells_labelled.txt', 'extract_bin.py', 'train.csv', 'extract_csv.py', 'Sentiment analysis.ipynb']


In [2]:
file_path = 'amazon_cells_labelled.txt'
data = extract_bin(file_path)
inputs = data.inputs
labels = data.labels
data = extract_bin("train_set_sentiment_final.txt")
input300 = data.inputs
labels300 = data.labels
inputs.extend(input300)
labels.extend(labels300)

split_object = split(inputs, labels, 1000)
train_inputs = split_object.train_set_inputs
train_labels = split_object.train_set_labels
test_inputs = split_object.test_set_inputs
test_labels = split_object.test_set_labels
print(train_inputs)
print(train_labels)

['So there is no way for me to plug it in here in the US unless I go by a converter.\t', 'Good case, Excellent value.\t', 'Great for the jawbone.\t', 'Tied to charger for conversations lasting more than 45 minutes.MAJOR PROBLEMS!!\t', 'The mic is great.\t', 'I have to jiggle the plug to get it to line up right to get decent volume.\t', 'If you have several dozen or several hundred contacts, then imagine the fun of sending each of them one by one.\t', 'If you are Razr owner...you must have this!\t', 'Needless to say, I wasted my money.\t', 'What a waste of money and time!.\t', 'And the sound quality is great.\t', 'He was very impressed when going from the original battery to the extended battery.\t', 'If the two were seperated by a mere 5+ ft I started to notice excessive static and garbled sound from the headset.\t', 'Very good quality though\t', 'The design is very odd, as the ear "clip" is not very comfortable at all.\t', 'Highly recommend for any one who has a blue tooth phone.\t', 

In [3]:
print(len(input300))

250


In [4]:

tokenizer = Tokenizer()
tokenizer.fit_on_texts(train_inputs)
print(tokenizer.word_index)
tokenized_inputs = tokenizer.texts_to_sequences(train_inputs)
print(tokenized_inputs)


{'the': 1, 'i': 2, 'and': 3, 'it': 4, 'is': 5, 'a': 6, 'this': 7, 'to': 8, 'phone': 9, 'my': 10, 'for': 11, 'of': 12, 'not': 13, 'with': 14, 'very': 15, 'great': 16, 'was': 17, 'on': 18, 'in': 19, 'that': 20, 'good': 21, 'have': 22, 'you': 23, 'product': 24, 'quality': 25, 'had': 26, 'headset': 27, 'works': 28, 'battery': 29, 'but': 30, 'as': 31, 'sound': 32, 'so': 33, 'are': 34, 'well': 35, 'one': 36, 'all': 37, 'use': 38, 'ear': 39, 'has': 40, 'would': 41, 'work': 42, 'from': 43, 'your': 44, 'like': 45, 'be': 46, 'me': 47, 'case': 48, 'if': 49, 'than': 50, "i've": 51, "don't": 52, 'no': 53, 'excellent': 54, 'up': 55, 'time': 56, "it's": 57, 'after': 58, 'price': 59, 'recommend': 60, 'does': 61, 'really': 62, '2': 63, 'at': 64, 'or': 65, 'best': 66, 'out': 67, 'only': 68, 'service': 69, 'get': 70, 'when': 71, 'nice': 72, "i'm": 73, 'also': 74, 'too': 75, 'just': 76, 'any': 77, 'new': 78, 'love': 79, 'these': 80, 'worked': 81, 'am': 82, 'charger': 83, 'more': 84, 'money': 85, 'do': 86,

In [5]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_inputs = pad_sequences(tokenized_inputs, padding='post')
train_labels = tf.convert_to_tensor(train_labels)
print(padded_inputs)


[[ 33 117   5 ...   0   0   0]
 [ 21  48  54 ...   0   0   0]
 [ 16  11   1 ...   0   0   0]
 ...
 [ 90  61  13 ...   0   0   0]
 [  1  68 139 ...   0   0   0]
 [ 23  87  13 ...   0   0   0]]


In [6]:
X = padded_inputs
Y = train_labels
print(X.shape)
print(Y.shape)
print(Y)

(1000, 30)
(1000,)
tf.Tensor(
[0 1 1 0 1 0 0 1 0 0 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1
 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1
 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1
 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 1 1 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 1 1 0 0 0 1 1 1 1 1 0 0 1 0 0
 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 0 0 0 1 1
 1 1 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 0 1 1
 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1 1
 1 1 0 0 0 0 0 1 0 0 1 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 1
 0 1 1 0 0 0 1 0 1 0 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 1 1 0 1 0
 1 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 0 0 0 0 0 1
 1 1 0 1 1 0 1 1 1 0 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 1

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [8]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=128))
model.add(LSTM(units=64, return_sequences=True))
model.add(LSTM(units=64))
model.add(Dense(units=1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# input_dim specify the vocab count, output_dim the dense vector dim, input_length the number of words in the sentence

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.fit(X, Y, epochs = 30)

Epoch 1/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.4773 - loss: 0.6957
Epoch 2/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.5469 - loss: 0.6686
Epoch 3/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.8854 - loss: 0.3468
Epoch 4/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.8828 - loss: 0.3157
Epoch 5/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 66ms/step - accuracy: 0.9605 - loss: 0.1506
Epoch 6/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - accuracy: 0.9878 - loss: 0.0515
Epoch 7/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - accuracy: 0.9914 - loss: 0.0479
Epoch 8/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9983 - loss: 0.0090
Epoch 9/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9952 - loss: 0.0184
Epoch 10/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9831 - loss: 0.0855
Epoch 11/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9851 - loss: 0.0603
Epoch 12/30
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy:

In [43]:
want_to_load = int(input("want to load model? [1/0]"))
if(want_to_load == 1):
    model = tf.keras.models.load_model('model.keras')
    print("model loaded")
def predict(model, tokenizer, input):
  tokenized_inputs = tokenizer.texts_to_sequences(input)
  padded_inputs = pad_sequences(tokenized_inputs, padding='post')
  predictions = model.predict(padded_inputs)
  return predictions

want to load model? [1/0]1
model loaded


/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_lib.py:713: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 11 variables whereas the saved optimizer has 20 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [44]:
accuracy = 0
for i in range(len(test_inputs)):
    print(i, ':', test_inputs[i])
    prediction = predict(model, tokenizer, [test_inputs[i]])
    print(prediction)

    if prediction > 0.5:
        predicted_label = 1
        print("Positive")
    else:
        predicted_label = 0
        print("Negative")
    if( predicted_label == test_labels[i]):
        accuracy += 1
    print(predict(model, tokenizer, [test_inputs[i]]))
accuracy = accuracy/len(test_inputs)
print(f'accuracy = {accuracy}')

0 : His achievement in the competition brought delight and a sense of pride to everyone.  
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step
[[0.2077377]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
[[0.2077377]]
1 : She smiled brightly, feeling confident after her hard work resulted in success.  
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step
[[0.45145676]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[0.45145676]]
2 : The team's victory was remarkable, and they celebrated their harmony and strength.  
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[0.52217394]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[0.52217394]]
3 : Their friendship was filled with generosity and trust, creating a joyful bond.  
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[0.68534964]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[0.68534964]]
4 : We admired her amazing talent and sincere effort during the performance.  
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[0.62255293]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[0.622552

In [30]:
text = "i though this was good but it is actually bad"
text_list = text.split()
for i in range(len(text_list)):
    if(text_list[i] not in tokenizer.word_index):
        print(text_list[i], ':not found')
for key, value in tokenizer.word_index.items():
    print(f'{key}:{value}')
prediction = predict(model, tokenizer, [text])
print(prediction)
if(prediction > 0.5):
    print("Positive")
else:
    print("Negative")

the:1
i:2
and:3
it:4
is:5
a:6
this:7
to:8
phone:9
my:10
for:11
of:12
not:13
with:14
very:15
great:16
was:17
on:18
in:19
that:20
good:21
have:22
you:23
product:24
quality:25
had:26
headset:27
works:28
battery:29
but:30
as:31
sound:32
so:33
are:34
well:35
one:36
all:37
use:38
ear:39
has:40
would:41
work:42
from:43
your:44
like:45
be:46
me:47
case:48
if:49
than:50
i've:51
don't:52
no:53
excellent:54
up:55
time:56
it's:57
after:58
price:59
recommend:60
does:61
really:62
2:63
at:64
or:65
best:66
out:67
only:68
service:69
get:70
when:71
nice:72
i'm:73
also:74
too:75
just:76
any:77
new:78
love:79
these:80
worked:81
am:82
charger:83
more:84
money:85
do:86
can:87
first:88
buy:89
item:90
better:91
an:92
ever:93
car:94
bluetooth:95
about:96
even:97
because:98
easy:99
then:100
what:101
comfortable:102
bought:103
now:104
they:105
reception:106
could:107
doesn't:108
its:109
did:110
used:111
poor:112
been:113
happy:114
which:115
will:116
there:117
waste:118
two:119
charge:120
made:121
still:122
off:1

In [28]:
print(len(tokenizer.word_index))


1878


In [42]:
tf.keras.models.save_model(model, 'model.keras')
os.listdir()

['train_set.txt',
 'train_set_sentiment.txt',
 '__pycache__',
 'trainDataSet.txt',
 'extract.py',
 'imdb_labelled.txt',
 'amazon_cells_labelled.txt',
 'extract_bin.py',
 'train.csv',
 'extract_csv.py',
 'Sentiment analysis.ipynb',
 'train_set_sentiment_final.txt',
 'model.h5',
 'model.keras']